.PHONY: ava like
all:
	@cat makefile
watch:
	npm run watch
ui:
	vue ui
test:
	npm run test
free:
	npm run free
selenium:
	npm run selenium-test
gen:
	node dataGen.js
link:
	npm link vue-selenium-unittest
	npm link mongodb-simple-query-syntax
	npm link ac-input
ava:
	npm run ava
ava2:
	npm run ava2
